# Generated by Django 6.0.5 on 2026-07-30 17:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='topuptransaction',
            name='cashback',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='topuptransaction',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='topuptransaction',
            name='provider_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='topuptransaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='topuptransaction',
            name='total_debited',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='topuptransaction',
            name='service_hub_txn_id',
            field=models.CharField(blank=True, help_text='Provider transaction ID (HimalPay / legacy Service Hub)', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='BankTransferTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('destination_bank', models.CharField(help_text='Bank code (e.g. LXBLNPKA)', max_length=50)),
                ('destination_bank_name', models.CharField(blank=True, default='', max_length=150)),
                ('destination_acc_no', models.CharField(max_length=50)),
                ('destination_acc_name', models.CharField(max_length=150)),
                ('is_destination_mobile', models.BooleanField(default=False)),
                ('transaction_remarks', models.CharField(default='Fund Transfer', max_length=255)),
                ('transaction_remarks_2', models.CharField(blank=True, default='', max_length=255)),
                ('transaction_remarks_3', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('merchant_txn_id', models.CharField(max_length=100, unique=True)),
                ('provider_txn_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cashback', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_debited', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('verified', models.BooleanField(default=False)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Transfer Transaction',
                'verbose_name_plural': 'Bank Transfer Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
