# Generated by Django 6.0.5 on 2026-07-31 20:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_deposit_screenshot_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], db_index=True, default='approved', help_text='Pending users can log in but cannot perform transactions until approved.', max_length=20),
        ),
        migrations.AddField(
            model_name='settings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Brand logo used across the app and as the favicon', null=True, upload_to='settings/logo/'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='config',
            field=models.JSONField(blank=True, default=core.models.default_app_config, help_text='Application-wide configuration'),
        ),
    ]
