# Generated by Django 6.0.5 on 2026-08-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_account_status_and_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Active')], db_index=True, default='approved', help_text='Pending users can log in but cannot perform transactions until set to Active.', max_length=20),
        ),
    ]
