# Generated by Django 6.0.5 on 2026-08-02 15:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_account_status_active_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemittanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(db_index=True, help_text='Remittance reference number', max_length=100)),
                ('samsara_link_id', models.CharField(blank=True, default='', help_text='core_transaction_uuid from SAMSARA_GET', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payout amount in NPR (rupees)', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('payout_currency', models.CharField(blank=True, default='NPR', max_length=10)),
                ('sender_name', models.CharField(blank=True, default='', max_length=200)),
                ('sender_address', models.CharField(blank=True, default='', max_length=255)),
                ('sender_city', models.CharField(blank=True, default='', max_length=100)),
                ('sender_country', models.CharField(blank=True, default='', max_length=100)),
                ('receiver_name', models.CharField(blank=True, default='', max_length=200)),
                ('receiver_phone', models.CharField(blank=True, default='', max_length=50)),
                ('receiver_country', models.CharField(blank=True, default='', max_length=100)),
                ('payment_type', models.CharField(blank=True, default='', max_length=50)),
                ('txn_date', models.CharField(blank=True, default='', max_length=80)),
                ('beneficiary_gender', models.CharField(blank=True, default='', max_length=20)),
                ('beneficiary_nationality', models.CharField(blank=True, default='Nepali', max_length=50)),
                ('beneficiary_state', models.CharField(blank=True, default='', max_length=100)),
                ('beneficiary_district', models.CharField(blank=True, default='', max_length=100)),
                ('beneficiary_municipality', models.CharField(blank=True, default='', max_length=150)),
                ('beneficiary_ward_number', models.CharField(blank=True, default='', max_length=20)),
                ('beneficiary_city', models.CharField(blank=True, default='', max_length=100)),
                ('beneficiary_address', models.CharField(blank=True, default='', max_length=255)),
                ('beneficiary_relation', models.CharField(blank=True, default='SELF', max_length=50)),
                ('beneficiary_occupation', models.CharField(blank=True, default='', max_length=100)),
                ('beneficiary_citizenship_number', models.CharField(blank=True, default='', max_length=100)),
                ('beneficiary_citizenship_issuing_district', models.CharField(blank=True, default='', max_length=100)),
                ('beneficiary_id_type', models.CharField(blank=True, default='Citizenship', max_length=50)),
                ('beneficiary_id_number', models.CharField(blank=True, default='', max_length=100)),
                ('beneficiary_id_issue_date', models.CharField(blank=True, default='', max_length=30)),
                ('beneficiary_id_issue_by', models.CharField(blank=True, default='', max_length=100)),
                ('beneficiary_mobile_no', models.CharField(blank=True, default='', max_length=50)),
                ('beneficiary_dob', models.CharField(blank=True, default='', max_length=30)),
                ('remittance_purpose', models.CharField(blank=True, default='FAMILY_SUPPORT', max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('merchant_txn_id', models.CharField(max_length=100, unique=True)),
                ('provider_txn_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cashback', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_credited', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('wallet_credited', models.BooleanField(default=False)),
                ('lookup_response', models.JSONField(blank=True, default=dict)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remittance_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remittance Transaction',
                'verbose_name_plural': 'Remittance Transactions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'success')), fields=('ref_no',), name='unique_successful_remittance_ref_no')],
            },
        ),
    ]
