# Generated by Django 6.0.5 on 2026-08-05 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='citizenship_number',
            field=models.CharField(blank=True, default='', help_text='Citizenship / national ID number from the latest KYC submission.', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kyc_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='not_submitted', help_text='Denormalized KYC status for fast access checks and field locking.', max_length=20),
        ),
        migrations.AlterField(
            model_name='walletadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('credit', 'Manual Load (Add Fund)'), ('debit', 'Debit')], max_length=10),
        ),
        migrations.CreateModel(
            name='KYCSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('citizenship_number', models.CharField(max_length=50)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who approved or rejected this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Submission',
                'verbose_name_plural': 'KYC Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('citizenship', 'Citizenship'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('national_id', 'National ID'), ('other', 'Other')], max_length=30)),
                ('side', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('single', 'Single')], default='single', max_length=10)),
                ('file', models.ImageField(help_text='Scanned or photographed identity document', upload_to='kyc/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.kycsubmission')),
            ],
            options={
                'verbose_name': 'KYC Document',
                'verbose_name_plural': 'KYC Documents',
                'ordering': ['uploaded_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KYCAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('document_uploaded', 'Document Uploaded'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('status_changed', 'Status Changed')], max_length=30)),
                ('old_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(blank=True, default='', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User or admin who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.kycsubmission')),
            ],
            options={
                'verbose_name': 'KYC Audit Log',
                'verbose_name_plural': 'KYC Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
