# Generated by Django 6.0.5 on 2026-08-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_kyc_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('document_uploaded', 'Document Uploaded'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('status_changed', 'Status Changed'), ('profile_updated', 'Profile Updated'), ('profile_lock_blocked', 'Profile Lock Blocked')], max_length=30),
        ),
    ]
