# Generated by Django 6.0.5 on 2026-08-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_statement_reconcile_logs_nullable'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='statementdiscrepancy',
            new_name='core_statem_status_e45676_idx',
            old_name='core_statem_status_4f0a8a_idx',
        ),
        migrations.RenameIndex(
            model_name='statementdiscrepancy',
            new_name='core_statem_transac_8f8213_idx',
            old_name='core_statem_transac_7c2e1b_idx',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='transaction_pin',
            field=models.CharField(blank=True, default='', help_text='Hashed transaction PIN (exactly 4 digits). Empty if not set.', max_length=128),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='bank_name',
            field=models.CharField(blank=True, default='', help_text='Payment method / source used for the deposit (bank name, Khalti, or eSewa)', max_length=120),
        ),
        migrations.AlterField(
            model_name='securityauditlog',
            name='action',
            field=models.CharField(choices=[('transaction_pin_set', 'Transaction PIN Set'), ('transaction_pin_changed', 'Transaction PIN Changed'), ('transaction_pin_reset', 'Transaction PIN Reset'), ('transaction_pin_reset_otp_sent', 'Transaction PIN Reset OTP Sent'), ('phone_change_otp_sent', 'Phone Change OTP Sent'), ('phone_changed', 'Phone Changed'), ('email_change_otp_sent', 'Email Change OTP Sent'), ('email_changed', 'Email Changed'), ('login_otp_sent', 'Login OTP Sent'), ('login_otp_verified', 'Login OTP Verified')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='settings',
            name='bank_details',
            field=models.JSONField(default=dict, help_text='Deposit payment accounts JSON: legacy bank_* fields plus accounts[] (bank/khalti/esewa)'),
        ),
    ]
