# Generated by Django — index name hash changed for HomePopupImpression

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_bank_transfer_commission_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='homepopupimpression',
            new_name='core_homepo_popup_i_c3de12_idx',
            old_name='core_homepo_popup_i_7a2c1d_idx',
        ),
    ]
