# Generated by Django 6.0 on 2026-08-16 10:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_wallet_transaction_block_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittancetransaction',
            name='citizenship_back',
            field=models.ImageField(blank=True, help_text='Citizenship back image kept after matching fails for admin review.', null=True, upload_to=core.models.remittance_citizenship_back_upload),
        ),
        migrations.AddField(
            model_name='remittancetransaction',
            name='citizenship_front',
            field=models.ImageField(blank=True, help_text='Citizenship front image kept after matching fails for admin review.', null=True, upload_to=core.models.remittance_citizenship_front_upload),
        ),
    ]
