# Generated by Django 6.0 on 2026-08-27 10:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_rename_core_wallet_sender__9c1e2a_idx_core_wallet_sender__bf643e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_dealer',
            field=models.ForeignKey(blank=True, help_text='Dealer this customer/agent/sub-agent belongs to. Used for commission.', limit_choices_to={'role': 'dealer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_remittance_transfer',
            field=models.BooleanField(db_index=True, default=True, help_text='When enabled, this user can look up and receive remittance fund transfers.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parent_agent',
            field=models.ForeignKey(blank=True, help_text='Parent Agent for Sub-Agent accounts.', limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('dealer', 'Dealer'), ('agent', 'Agent'), ('sub_agent', 'Sub-Agent')], db_index=True, default='customer', help_text='Business hierarchy role: Admin (staff) → Dealer → Agent → Sub-Agent → Customer.', max_length=20),
        ),
        migrations.AddField(
            model_name='wallet',
            name='freeze_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='wallet',
            name='freeze_unfrozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='freeze_unfrozen_by',
            field=models.ForeignKey(blank=True, help_text='Admin who last unfroze this wallet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallets_freeze_unfrozen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallet',
            name='frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='frozen_by',
            field=models.ForeignKey(blank=True, help_text='Admin who last froze this wallet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallets_frozen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_frozen',
            field=models.BooleanField(db_index=True, default=False,             help_text='When True, all wallet debit/credit operations are blocked until an admin unfreezes. Separate from transactions_blocked (HimalPay mismatch lock).'),
        ),
        migrations.CreateModel(
            name='DealerCommissionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Percent of transaction amount paid as gross commission to this Dealer.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tds_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Percent TDS deducted from gross commission. Null = use global default.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_commission_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dealer Commission Config',
                'verbose_name_plural': 'Dealer Commission Configs',
            },
        ),
        migrations.CreateModel(
            name='DealerCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('topup', 'Top-up'), ('data_pack', 'Data pack'), ('internet', 'Internet'), ('water', 'Water'), ('electricity', 'Electricity'), ('community_electricity', 'Community electricity'), ('bank_transfer', 'Bank transfer'), ('remittance', 'Remittance')], db_index=True, max_length=40)),
                ('txn_id', models.PositiveIntegerField()),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('txn_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('gross_commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tds_rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('tds_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('reversed', 'Reversed')], db_index=True, default='posted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_commissions', to=settings.AUTH_USER_MODEL)),
                ('source_user', models.ForeignKey(blank=True, help_text='Customer (or agent) whose transaction generated this commission.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_dealer_commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dealer Commission',
                'verbose_name_plural': 'Dealer Commissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dealer', '-created_at'], name='core_dealerc_dealer__idx'), models.Index(fields=['source_user', '-created_at'], name='core_dealerc_source__idx')],
                'constraints': [models.UniqueConstraint(fields=('txn_type', 'txn_id'), name='uniq_dealer_commission_txn')],
            },
        ),
    ]
