# Generated by Django 6.0 on 2026-08-27 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_merge_0045_apk_and_hierarchy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_message_preview', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_threads_as_high', to=settings.AUTH_USER_MODEL)),
                ('user_low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_threads_as_low', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Chat Thread',
                'verbose_name_plural': 'Support Chat Threads',
            },
        ),
        migrations.CreateModel(
            name='SupportChatReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_chat_reads', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='core.supportchatthread')),
            ],
            options={
                'verbose_name': 'Support Chat Read State',
                'verbose_name_plural': 'Support Chat Read States',
            },
        ),
        migrations.CreateModel(
            name='SupportChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.supportchatthread')),
            ],
            options={
                'verbose_name': 'Support Chat Message',
                'verbose_name_plural': 'Support Chat Messages',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='supportchatthread',
            index=models.Index(fields=['user_low', 'last_message_at'], name='core_spt_low_last_idx'),
        ),
        migrations.AddIndex(
            model_name='supportchatthread',
            index=models.Index(fields=['user_high', 'last_message_at'], name='core_spt_high_last_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportchatthread',
            constraint=models.UniqueConstraint(fields=('user_low', 'user_high'), name='uniq_support_chat_thread_pair'),
        ),
        migrations.AddConstraint(
            model_name='supportchatreadstate',
            constraint=models.UniqueConstraint(fields=('thread', 'user'), name='uniq_support_chat_read_user'),
        ),
        migrations.AddIndex(
            model_name='supportchatmessage',
            index=models.Index(fields=['thread', 'created_at'], name='core_spt_msg_thread_idx'),
        ),
    ]
