# Generated by Django 6.0 on 2026-08-28 11:20

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_three_roles_service_charges'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerPayoutAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('bank', 'Bank Account'), ('khalti', 'Khalti'), ('esewa', 'eSewa')], db_index=True, max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('account_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(help_text='Bank account number, eSewa ID, or Khalti ID', max_length=80)),
                ('bank_name', models.CharField(blank=True, default='', max_length=120)),
                ('branch', models.CharField(blank=True, default='', max_length=120)),
                ('qr_code', models.ImageField(blank=True, help_text='QR code for this payout account', null=True, upload_to=core.models.dealer_payout_qr_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif'])])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(limit_choices_to={'role': 'dealer'}, on_delete=django.db.models.deletion.CASCADE, related_name='payout_accounts', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_accounts_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dealer Payout Account',
                'verbose_name_plural': 'Dealer Payout Accounts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='deposit',
            name='payout_account',
            field=models.ForeignKey(blank=True, help_text='Dealer payout account used for this load, if the user paid a Dealer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='core.dealerpayoutaccount'),
        ),
        migrations.AddIndex(
            model_name='dealerpayoutaccount',
            index=models.Index(fields=['dealer', 'status'], name='core_payout_dealer_st_idx'),
        ),
    ]
