# Generated by Django 6.0 on 2026-08-28 11:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_merge_0047_alter_and_0049_payout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealercommission',
            name='txn_type',
            field=models.CharField(choices=[('topup', 'Top-up'), ('data_pack', 'Data pack'), ('internet', 'Internet'), ('water', 'Water'), ('electricity', 'Electricity'), ('community_electricity', 'Community electricity'), ('bank_transfer', 'Bank transfer'), ('remittance', 'Remittance'), ('wallet_transfer', 'Wallet transfer')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='servicechargeconfig',
            name='dealer_commission_flat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Flat dealer commission in Rs. Applied only when the User has an assigned Dealer.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='servicechargeconfig',
            name='dealer_commission_percent',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Dealer commission as a percent of the transaction amount.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='servicechargeconfig',
            name='himalpay_charge_flat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Configured HimalPay charge in Rs. When zero, the live provider charge is used.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='servicechargeconfig',
            name='himalpay_charge_percent',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='HimalPay charge as a percent of the transaction amount.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='servicechargeconfig',
            name='system_charge_flat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Flat MySewa system charge in Rs.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='servicechargeconfig',
            name='system_charge_percent',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='MySewa system charge as a percent of the transaction amount.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
