# Generated by Django 6.0 on 2026-08-29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def zero_dealer_commission_percent(apps, schema_editor):
    ServiceChargeConfig = apps.get_model('core', 'ServiceChargeConfig')
    ServiceChargeConfig.objects.update(dealer_commission_percent=Decimal('0.0000'))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_dealercommission_txn_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealercommission',
            name='commission_rate',
            field=models.DecimalField(
                decimal_places=2,
                help_text='Applied flat dealer commission in Rs snapshotted at posting time.',
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name='dealercommissionconfig',
            name='commission_rate',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Flat gross commission in Rs paid to this Dealer per transaction (or downline user).',
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal('0'))],
            ),
        ),
        migrations.AlterField(
            model_name='servicecommissionrule',
            name='dealer_rate',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text="Flat dealer commission in Rs for this service. Zero uses the Dealer's default amount.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal('0'))],
            ),
        ),
        migrations.AlterField(
            model_name='servicechargeconfig',
            name='dealer_commission_percent',
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal('0.0000'),
                help_text='Unused. Dealer commission is a flat Rs amount only.',
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(Decimal('0'))],
            ),
        ),
        migrations.RunPython(zero_dealer_commission_percent, migrations.RunPython.noop),
    ]
