# Generated by Django 6.0

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_wallet_balance_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportchatmessage',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supportchatmessage',
            name='kind',
            field=models.CharField(
                choices=[
                    ('text', 'Text'),
                    ('image', 'Image'),
                    ('video', 'Video'),
                    ('file', 'File'),
                ],
                db_index=True,
                default='text',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='supportchatmessage',
            name='attachment',
            field=models.FileField(
                blank=True,
                null=True,
                storage=core.models._support_chat_file_storage,
                upload_to=core.models.support_chat_attachment_upload_to,
            ),
        ),
        migrations.AddField(
            model_name='supportchatmessage',
            name='attachment_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='supportchatmessage',
            name='attachment_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supportchatmessage',
            name='attachment_content_type',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='supportchatmessage',
            name='client_nonce',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='supportchatmessage',
            constraint=models.UniqueConstraint(
                fields=('thread', 'client_nonce'),
                name='uniq_support_chat_msg_nonce',
            ),
        ),
    ]
