/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCommissionHistoryRouteImport } from './routes/admin/commission-history'
import { Route as AdminCommunityElectricityRouteImport } from './routes/admin/community-electricity'
import { Route as AdminDataTopupsRouteImport } from './routes/admin/data-topups'
import { Route as AdminDealerProfitRouteImport } from './routes/admin/dealer-profit'
import { Route as AdminDealersRouteImport } from './routes/admin/dealers'
import { Route as AdminDepositsRouteImport } from './routes/admin/deposits'
import { Route as AdminHierarchyRouteImport } from './routes/admin/hierarchy'
import { Route as AdminHimalpayHistoryRouteImport } from './routes/admin/himalpay-history'
import { Route as AdminInternetRouteImport } from './routes/admin/internet'
import { Route as AdminKycRouteImport } from './routes/admin/kyc'
import { Route as AdminPopupsRouteImport } from './routes/admin/popups'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminPushRouteImport } from './routes/admin/push'
import { Route as AdminRemittancesRouteImport } from './routes/admin/remittances'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminStatementRouteImport } from './routes/admin/statement'
import { Route as AdminSupportChatRouteImport } from './routes/admin/support-chat'
import { Route as AdminTopupsRouteImport } from './routes/admin/topups'
import { Route as AdminTransactionHistoryRouteImport } from './routes/admin/transaction-history'
import { Route as AdminTransfersRouteImport } from './routes/admin/transfers'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminWalletsRouteImport } from './routes/admin/wallets'
import { Route as AdminWaterRouteImport } from './routes/admin/water'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCommunityElectricityRouteImport } from './routes/app/community-electricity'
import { Route as AppDataTopupRouteImport } from './routes/app/data-topup'
import { Route as AppElectricityRouteImport } from './routes/app/electricity'
import { Route as AppHistoryRouteImport } from './routes/app/history'
import { Route as AppInternetRouteImport } from './routes/app/internet'
import { Route as AppLoadRouteImport } from './routes/app/load'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppRemittanceRouteImport } from './routes/app/remittance'
import { Route as AppScanRouteImport } from './routes/app/scan'
import { Route as AppServicesRouteImport } from './routes/app/services'
import { Route as AppSupportChatRouteImport } from './routes/app/support-chat'
import { Route as AppTopupRouteImport } from './routes/app/topup'
import { Route as AppTransferRouteImport } from './routes/app/transfer'
import { Route as AppWalletHistoryRouteImport } from './routes/app/wallet-history'
import { Route as AppWaterRouteImport } from './routes/app/water'
import { Route as DealerIndexRouteImport } from './routes/dealer/index'
import { Route as DealerCommissionRouteImport } from './routes/dealer/commission'
import { Route as DealerCustomersRouteImport } from './routes/dealer/customers'
import { Route as DealerProfileRouteImport } from './routes/dealer/profile'
import { Route as DealerReportsRouteImport } from './routes/dealer/reports'
import { Route as DealerSubAgentsRouteImport } from './routes/dealer/sub-agents'
import { Route as DealerTransactionsRouteImport } from './routes/dealer/transactions'
import { Route as AdminCommunityElectricityCommunityElectricityIdRouteImport } from './routes/admin/community-electricity_.$communityElectricityId'
import { Route as AdminDataTopupsDataTopupIdRouteImport } from './routes/admin/data-topups_.$dataTopupId'
import { Route as AdminDepositsDepositIdRouteImport } from './routes/admin/deposits_.$depositId'
import { Route as AdminInternetInternetIdRouteImport } from './routes/admin/internet_.$internetId'
import { Route as AdminKycKycIdRouteImport } from './routes/admin/kyc_.$kycId'
import { Route as AdminTopupsTopupIdRouteImport } from './routes/admin/topups_.$topupId'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users_.$userId'
import { Route as AdminUsersNewRouteImport } from './routes/admin/users_.new'
import { Route as AdminWalletsWalletIdRouteImport } from './routes/admin/wallets_.$walletId'
import { Route as AdminWaterWaterIdRouteImport } from './routes/admin/water_.$waterId'
import { Route as AppHistoryActivityIdRouteImport } from './routes/app/history_.$activityId'
import { Route as AppNotificationsNotificationIdRouteImport } from './routes/app/notifications_.$notificationId'
import { Route as AppProfileEditRouteImport } from './routes/app/profile_.edit'
import { Route as AppProfileEmailRouteImport } from './routes/app/profile_.email'
import { Route as AppProfileKycRouteImport } from './routes/app/profile_.kyc'
import { Route as AppProfilePasswordRouteImport } from './routes/app/profile_.password'
import { Route as AppProfilePhoneRouteImport } from './routes/app/profile_.phone'
import { Route as AppProfilePinRouteImport } from './routes/app/profile_.pin'
import { Route as AdminUsersUserIdEditRouteImport } from './routes/admin/users_.$userId_.edit'
import { Route as AdminUsersUserIdReportRouteImport } from './routes/admin/users_.$userId_.report'
import { Route as AdminWalletsWalletIdEditRouteImport } from './routes/admin/wallets_.$walletId_.edit'
import { Route as AdminWalletsWalletIdTransactionsRouteImport } from './routes/admin/wallets_.$walletId_.transactions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommissionHistoryRoute = AdminCommissionHistoryRouteImport.update({
  id: '/admin/commission-history',
  path: '/admin/commission-history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommunityElectricityRoute =
  AdminCommunityElectricityRouteImport.update({
    id: '/admin/community-electricity',
    path: '/admin/community-electricity',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDataTopupsRoute = AdminDataTopupsRouteImport.update({
  id: '/admin/data-topups',
  path: '/admin/data-topups',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDealerProfitRoute = AdminDealerProfitRouteImport.update({
  id: '/admin/dealer-profit',
  path: '/admin/dealer-profit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDealersRoute = AdminDealersRouteImport.update({
  id: '/admin/dealers',
  path: '/admin/dealers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepositsRoute = AdminDepositsRouteImport.update({
  id: '/admin/deposits',
  path: '/admin/deposits',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHierarchyRoute = AdminHierarchyRouteImport.update({
  id: '/admin/hierarchy',
  path: '/admin/hierarchy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHimalpayHistoryRoute = AdminHimalpayHistoryRouteImport.update({
  id: '/admin/himalpay-history',
  path: '/admin/himalpay-history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInternetRoute = AdminInternetRouteImport.update({
  id: '/admin/internet',
  path: '/admin/internet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/admin/kyc',
  path: '/admin/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPopupsRoute = AdminPopupsRouteImport.update({
  id: '/admin/popups',
  path: '/admin/popups',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPushRoute = AdminPushRouteImport.update({
  id: '/admin/push',
  path: '/admin/push',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRemittancesRoute = AdminRemittancesRouteImport.update({
  id: '/admin/remittances',
  path: '/admin/remittances',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatementRoute = AdminStatementRouteImport.update({
  id: '/admin/statement',
  path: '/admin/statement',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportChatRoute = AdminSupportChatRouteImport.update({
  id: '/admin/support-chat',
  path: '/admin/support-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTopupsRoute = AdminTopupsRouteImport.update({
  id: '/admin/topups',
  path: '/admin/topups',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionHistoryRoute = AdminTransactionHistoryRouteImport.update({
  id: '/admin/transaction-history',
  path: '/admin/transaction-history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransfersRoute = AdminTransfersRouteImport.update({
  id: '/admin/transfers',
  path: '/admin/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/admin/wallets',
  path: '/admin/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWaterRoute = AdminWaterRouteImport.update({
  id: '/admin/water',
  path: '/admin/water',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCommunityElectricityRoute = AppCommunityElectricityRouteImport.update({
  id: '/app/community-electricity',
  path: '/app/community-electricity',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDataTopupRoute = AppDataTopupRouteImport.update({
  id: '/app/data-topup',
  path: '/app/data-topup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppElectricityRoute = AppElectricityRouteImport.update({
  id: '/app/electricity',
  path: '/app/electricity',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/app/history',
  path: '/app/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInternetRoute = AppInternetRouteImport.update({
  id: '/app/internet',
  path: '/app/internet',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoadRoute = AppLoadRouteImport.update({
  id: '/app/load',
  path: '/app/load',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/app/notifications',
  path: '/app/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRemittanceRoute = AppRemittanceRouteImport.update({
  id: '/app/remittance',
  path: '/app/remittance',
  getParentRoute: () => rootRouteImport,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/app/scan',
  path: '/app/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/app/services',
  path: '/app/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSupportChatRoute = AppSupportChatRouteImport.update({
  id: '/app/support-chat',
  path: '/app/support-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTopupRoute = AppTopupRouteImport.update({
  id: '/app/topup',
  path: '/app/topup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransferRoute = AppTransferRouteImport.update({
  id: '/app/transfer',
  path: '/app/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletHistoryRoute = AppWalletHistoryRouteImport.update({
  id: '/app/wallet-history',
  path: '/app/wallet-history',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWaterRoute = AppWaterRouteImport.update({
  id: '/app/water',
  path: '/app/water',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerIndexRoute = DealerIndexRouteImport.update({
  id: '/dealer/',
  path: '/dealer/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerCommissionRoute = DealerCommissionRouteImport.update({
  id: '/dealer/commission',
  path: '/dealer/commission',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerCustomersRoute = DealerCustomersRouteImport.update({
  id: '/dealer/customers',
  path: '/dealer/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerProfileRoute = DealerProfileRouteImport.update({
  id: '/dealer/profile',
  path: '/dealer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerReportsRoute = DealerReportsRouteImport.update({
  id: '/dealer/reports',
  path: '/dealer/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerSubAgentsRoute = DealerSubAgentsRouteImport.update({
  id: '/dealer/sub-agents',
  path: '/dealer/sub-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const DealerTransactionsRoute = DealerTransactionsRouteImport.update({
  id: '/dealer/transactions',
  path: '/dealer/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommunityElectricityCommunityElectricityIdRoute =
  AdminCommunityElectricityCommunityElectricityIdRouteImport.update({
    id: '/admin/community-electricity_/$communityElectricityId',
    path: '/admin/community-electricity/$communityElectricityId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDataTopupsDataTopupIdRoute =
  AdminDataTopupsDataTopupIdRouteImport.update({
    id: '/admin/data-topups_/$dataTopupId',
    path: '/admin/data-topups/$dataTopupId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDepositsDepositIdRoute = AdminDepositsDepositIdRouteImport.update({
  id: '/admin/deposits_/$depositId',
  path: '/admin/deposits/$depositId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInternetInternetIdRoute = AdminInternetInternetIdRouteImport.update({
  id: '/admin/internet_/$internetId',
  path: '/admin/internet/$internetId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKycKycIdRoute = AdminKycKycIdRouteImport.update({
  id: '/admin/kyc_/$kycId',
  path: '/admin/kyc/$kycId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTopupsTopupIdRoute = AdminTopupsTopupIdRouteImport.update({
  id: '/admin/topups_/$topupId',
  path: '/admin/topups/$topupId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/admin/users_/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersNewRoute = AdminUsersNewRouteImport.update({
  id: '/admin/users_/new',
  path: '/admin/users/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletsWalletIdRoute = AdminWalletsWalletIdRouteImport.update({
  id: '/admin/wallets_/$walletId',
  path: '/admin/wallets/$walletId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWaterWaterIdRoute = AdminWaterWaterIdRouteImport.update({
  id: '/admin/water_/$waterId',
  path: '/admin/water/$waterId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHistoryActivityIdRoute = AppHistoryActivityIdRouteImport.update({
  id: '/app/history_/$activityId',
  path: '/app/history/$activityId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotificationsNotificationIdRoute =
  AppNotificationsNotificationIdRouteImport.update({
    id: '/app/notifications_/$notificationId',
    path: '/app/notifications/$notificationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppProfileEditRoute = AppProfileEditRouteImport.update({
  id: '/app/profile_/edit',
  path: '/app/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileEmailRoute = AppProfileEmailRouteImport.update({
  id: '/app/profile_/email',
  path: '/app/profile/email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileKycRoute = AppProfileKycRouteImport.update({
  id: '/app/profile_/kyc',
  path: '/app/profile/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfilePasswordRoute = AppProfilePasswordRouteImport.update({
  id: '/app/profile_/password',
  path: '/app/profile/password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfilePhoneRoute = AppProfilePhoneRouteImport.update({
  id: '/app/profile_/phone',
  path: '/app/profile/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfilePinRoute = AppProfilePinRouteImport.update({
  id: '/app/profile_/pin',
  path: '/app/profile/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdEditRoute = AdminUsersUserIdEditRouteImport.update({
  id: '/admin/users_/$userId_/edit',
  path: '/admin/users/$userId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdReportRoute = AdminUsersUserIdReportRouteImport.update({
  id: '/admin/users_/$userId_/report',
  path: '/admin/users/$userId/report',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletsWalletIdEditRoute =
  AdminWalletsWalletIdEditRouteImport.update({
    id: '/admin/wallets_/$walletId_/edit',
    path: '/admin/wallets/$walletId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminWalletsWalletIdTransactionsRoute =
  AdminWalletsWalletIdTransactionsRouteImport.update({
    id: '/admin/wallets_/$walletId_/transactions',
    path: '/admin/wallets/$walletId/transactions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/admin/commission-history': typeof AdminCommissionHistoryRoute
  '/admin/community-electricity': typeof AdminCommunityElectricityRoute
  '/admin/data-topups': typeof AdminDataTopupsRoute
  '/admin/dealer-profit': typeof AdminDealerProfitRoute
  '/admin/dealers': typeof AdminDealersRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/hierarchy': typeof AdminHierarchyRoute
  '/admin/himalpay-history': typeof AdminHimalpayHistoryRoute
  '/admin/internet': typeof AdminInternetRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/popups': typeof AdminPopupsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/push': typeof AdminPushRoute
  '/admin/remittances': typeof AdminRemittancesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/statement': typeof AdminStatementRoute
  '/admin/support-chat': typeof AdminSupportChatRoute
  '/admin/topups': typeof AdminTopupsRoute
  '/admin/transaction-history': typeof AdminTransactionHistoryRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/water': typeof AdminWaterRoute
  '/app/community-electricity': typeof AppCommunityElectricityRoute
  '/app/data-topup': typeof AppDataTopupRoute
  '/app/electricity': typeof AppElectricityRoute
  '/app/history': typeof AppHistoryRoute
  '/app/internet': typeof AppInternetRoute
  '/app/load': typeof AppLoadRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/remittance': typeof AppRemittanceRoute
  '/app/scan': typeof AppScanRoute
  '/app/services': typeof AppServicesRoute
  '/app/support-chat': typeof AppSupportChatRoute
  '/app/topup': typeof AppTopupRoute
  '/app/transfer': typeof AppTransferRoute
  '/app/wallet-history': typeof AppWalletHistoryRoute
  '/app/water': typeof AppWaterRoute
  '/dealer/commission': typeof DealerCommissionRoute
  '/dealer/customers': typeof DealerCustomersRoute
  '/dealer/profile': typeof DealerProfileRoute
  '/dealer/reports': typeof DealerReportsRoute
  '/dealer/sub-agents': typeof DealerSubAgentsRoute
  '/dealer/transactions': typeof DealerTransactionsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/dealer/': typeof DealerIndexRoute
  '/admin/community-electricity/$communityElectricityId': typeof AdminCommunityElectricityCommunityElectricityIdRoute
  '/admin/data-topups/$dataTopupId': typeof AdminDataTopupsDataTopupIdRoute
  '/admin/deposits/$depositId': typeof AdminDepositsDepositIdRoute
  '/admin/internet/$internetId': typeof AdminInternetInternetIdRoute
  '/admin/kyc/$kycId': typeof AdminKycKycIdRoute
  '/admin/topups/$topupId': typeof AdminTopupsTopupIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/wallets/$walletId': typeof AdminWalletsWalletIdRoute
  '/admin/water/$waterId': typeof AdminWaterWaterIdRoute
  '/app/history/$activityId': typeof AppHistoryActivityIdRoute
  '/app/notifications/$notificationId': typeof AppNotificationsNotificationIdRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/profile/email': typeof AppProfileEmailRoute
  '/app/profile/kyc': typeof AppProfileKycRoute
  '/app/profile/password': typeof AppProfilePasswordRoute
  '/app/profile/phone': typeof AppProfilePhoneRoute
  '/app/profile/pin': typeof AppProfilePinRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
  '/admin/users/$userId/report': typeof AdminUsersUserIdReportRoute
  '/admin/wallets/$walletId/edit': typeof AdminWalletsWalletIdEditRoute
  '/admin/wallets/$walletId/transactions': typeof AdminWalletsWalletIdTransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/admin/commission-history': typeof AdminCommissionHistoryRoute
  '/admin/community-electricity': typeof AdminCommunityElectricityRoute
  '/admin/data-topups': typeof AdminDataTopupsRoute
  '/admin/dealer-profit': typeof AdminDealerProfitRoute
  '/admin/dealers': typeof AdminDealersRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/hierarchy': typeof AdminHierarchyRoute
  '/admin/himalpay-history': typeof AdminHimalpayHistoryRoute
  '/admin/internet': typeof AdminInternetRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/popups': typeof AdminPopupsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/push': typeof AdminPushRoute
  '/admin/remittances': typeof AdminRemittancesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/statement': typeof AdminStatementRoute
  '/admin/support-chat': typeof AdminSupportChatRoute
  '/admin/topups': typeof AdminTopupsRoute
  '/admin/transaction-history': typeof AdminTransactionHistoryRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/water': typeof AdminWaterRoute
  '/app/community-electricity': typeof AppCommunityElectricityRoute
  '/app/data-topup': typeof AppDataTopupRoute
  '/app/electricity': typeof AppElectricityRoute
  '/app/history': typeof AppHistoryRoute
  '/app/internet': typeof AppInternetRoute
  '/app/load': typeof AppLoadRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/remittance': typeof AppRemittanceRoute
  '/app/scan': typeof AppScanRoute
  '/app/services': typeof AppServicesRoute
  '/app/support-chat': typeof AppSupportChatRoute
  '/app/topup': typeof AppTopupRoute
  '/app/transfer': typeof AppTransferRoute
  '/app/wallet-history': typeof AppWalletHistoryRoute
  '/app/water': typeof AppWaterRoute
  '/dealer/commission': typeof DealerCommissionRoute
  '/dealer/customers': typeof DealerCustomersRoute
  '/dealer/profile': typeof DealerProfileRoute
  '/dealer/reports': typeof DealerReportsRoute
  '/dealer/sub-agents': typeof DealerSubAgentsRoute
  '/dealer/transactions': typeof DealerTransactionsRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/dealer': typeof DealerIndexRoute
  '/admin/community-electricity/$communityElectricityId': typeof AdminCommunityElectricityCommunityElectricityIdRoute
  '/admin/data-topups/$dataTopupId': typeof AdminDataTopupsDataTopupIdRoute
  '/admin/deposits/$depositId': typeof AdminDepositsDepositIdRoute
  '/admin/internet/$internetId': typeof AdminInternetInternetIdRoute
  '/admin/kyc/$kycId': typeof AdminKycKycIdRoute
  '/admin/topups/$topupId': typeof AdminTopupsTopupIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/wallets/$walletId': typeof AdminWalletsWalletIdRoute
  '/admin/water/$waterId': typeof AdminWaterWaterIdRoute
  '/app/history/$activityId': typeof AppHistoryActivityIdRoute
  '/app/notifications/$notificationId': typeof AppNotificationsNotificationIdRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/profile/email': typeof AppProfileEmailRoute
  '/app/profile/kyc': typeof AppProfileKycRoute
  '/app/profile/password': typeof AppProfilePasswordRoute
  '/app/profile/phone': typeof AppProfilePhoneRoute
  '/app/profile/pin': typeof AppProfilePinRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
  '/admin/users/$userId/report': typeof AdminUsersUserIdReportRoute
  '/admin/wallets/$walletId/edit': typeof AdminWalletsWalletIdEditRoute
  '/admin/wallets/$walletId/transactions': typeof AdminWalletsWalletIdTransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/admin/commission-history': typeof AdminCommissionHistoryRoute
  '/admin/community-electricity': typeof AdminCommunityElectricityRoute
  '/admin/data-topups': typeof AdminDataTopupsRoute
  '/admin/dealer-profit': typeof AdminDealerProfitRoute
  '/admin/dealers': typeof AdminDealersRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/hierarchy': typeof AdminHierarchyRoute
  '/admin/himalpay-history': typeof AdminHimalpayHistoryRoute
  '/admin/internet': typeof AdminInternetRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/popups': typeof AdminPopupsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/push': typeof AdminPushRoute
  '/admin/remittances': typeof AdminRemittancesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/statement': typeof AdminStatementRoute
  '/admin/support-chat': typeof AdminSupportChatRoute
  '/admin/topups': typeof AdminTopupsRoute
  '/admin/transaction-history': typeof AdminTransactionHistoryRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/water': typeof AdminWaterRoute
  '/app/community-electricity': typeof AppCommunityElectricityRoute
  '/app/data-topup': typeof AppDataTopupRoute
  '/app/electricity': typeof AppElectricityRoute
  '/app/history': typeof AppHistoryRoute
  '/app/internet': typeof AppInternetRoute
  '/app/load': typeof AppLoadRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/remittance': typeof AppRemittanceRoute
  '/app/scan': typeof AppScanRoute
  '/app/services': typeof AppServicesRoute
  '/app/support-chat': typeof AppSupportChatRoute
  '/app/topup': typeof AppTopupRoute
  '/app/transfer': typeof AppTransferRoute
  '/app/wallet-history': typeof AppWalletHistoryRoute
  '/app/water': typeof AppWaterRoute
  '/dealer/commission': typeof DealerCommissionRoute
  '/dealer/customers': typeof DealerCustomersRoute
  '/dealer/profile': typeof DealerProfileRoute
  '/dealer/reports': typeof DealerReportsRoute
  '/dealer/sub-agents': typeof DealerSubAgentsRoute
  '/dealer/transactions': typeof DealerTransactionsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/dealer/': typeof DealerIndexRoute
  '/admin/community-electricity_/$communityElectricityId': typeof AdminCommunityElectricityCommunityElectricityIdRoute
  '/admin/data-topups_/$dataTopupId': typeof AdminDataTopupsDataTopupIdRoute
  '/admin/deposits_/$depositId': typeof AdminDepositsDepositIdRoute
  '/admin/internet_/$internetId': typeof AdminInternetInternetIdRoute
  '/admin/kyc_/$kycId': typeof AdminKycKycIdRoute
  '/admin/topups_/$topupId': typeof AdminTopupsTopupIdRoute
  '/admin/users_/$userId': typeof AdminUsersUserIdRoute
  '/admin/users_/new': typeof AdminUsersNewRoute
  '/admin/wallets_/$walletId': typeof AdminWalletsWalletIdRoute
  '/admin/water_/$waterId': typeof AdminWaterWaterIdRoute
  '/app/history_/$activityId': typeof AppHistoryActivityIdRoute
  '/app/notifications_/$notificationId': typeof AppNotificationsNotificationIdRoute
  '/app/profile_/edit': typeof AppProfileEditRoute
  '/app/profile_/email': typeof AppProfileEmailRoute
  '/app/profile_/kyc': typeof AppProfileKycRoute
  '/app/profile_/password': typeof AppProfilePasswordRoute
  '/app/profile_/phone': typeof AppProfilePhoneRoute
  '/app/profile_/pin': typeof AppProfilePinRoute
  '/admin/users_/$userId_/edit': typeof AdminUsersUserIdEditRoute
  '/admin/users_/$userId_/report': typeof AdminUsersUserIdReportRoute
  '/admin/wallets_/$walletId_/edit': typeof AdminWalletsWalletIdEditRoute
  '/admin/wallets_/$walletId_/transactions': typeof AdminWalletsWalletIdTransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/register'
    | '/admin/commission-history'
    | '/admin/community-electricity'
    | '/admin/data-topups'
    | '/admin/dealer-profit'
    | '/admin/dealers'
    | '/admin/deposits'
    | '/admin/hierarchy'
    | '/admin/himalpay-history'
    | '/admin/internet'
    | '/admin/kyc'
    | '/admin/popups'
    | '/admin/profile'
    | '/admin/push'
    | '/admin/remittances'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/statement'
    | '/admin/support-chat'
    | '/admin/topups'
    | '/admin/transaction-history'
    | '/admin/transfers'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/water'
    | '/app/community-electricity'
    | '/app/data-topup'
    | '/app/electricity'
    | '/app/history'
    | '/app/internet'
    | '/app/load'
    | '/app/notifications'
    | '/app/profile'
    | '/app/remittance'
    | '/app/scan'
    | '/app/services'
    | '/app/support-chat'
    | '/app/topup'
    | '/app/transfer'
    | '/app/wallet-history'
    | '/app/water'
    | '/dealer/commission'
    | '/dealer/customers'
    | '/dealer/profile'
    | '/dealer/reports'
    | '/dealer/sub-agents'
    | '/dealer/transactions'
    | '/admin/'
    | '/app/'
    | '/dealer/'
    | '/admin/community-electricity/$communityElectricityId'
    | '/admin/data-topups/$dataTopupId'
    | '/admin/deposits/$depositId'
    | '/admin/internet/$internetId'
    | '/admin/kyc/$kycId'
    | '/admin/topups/$topupId'
    | '/admin/users/$userId'
    | '/admin/users/new'
    | '/admin/wallets/$walletId'
    | '/admin/water/$waterId'
    | '/app/history/$activityId'
    | '/app/notifications/$notificationId'
    | '/app/profile/edit'
    | '/app/profile/email'
    | '/app/profile/kyc'
    | '/app/profile/password'
    | '/app/profile/phone'
    | '/app/profile/pin'
    | '/admin/users/$userId/edit'
    | '/admin/users/$userId/report'
    | '/admin/wallets/$walletId/edit'
    | '/admin/wallets/$walletId/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/register'
    | '/admin/commission-history'
    | '/admin/community-electricity'
    | '/admin/data-topups'
    | '/admin/dealer-profit'
    | '/admin/dealers'
    | '/admin/deposits'
    | '/admin/hierarchy'
    | '/admin/himalpay-history'
    | '/admin/internet'
    | '/admin/kyc'
    | '/admin/popups'
    | '/admin/profile'
    | '/admin/push'
    | '/admin/remittances'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/statement'
    | '/admin/support-chat'
    | '/admin/topups'
    | '/admin/transaction-history'
    | '/admin/transfers'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/water'
    | '/app/community-electricity'
    | '/app/data-topup'
    | '/app/electricity'
    | '/app/history'
    | '/app/internet'
    | '/app/load'
    | '/app/notifications'
    | '/app/profile'
    | '/app/remittance'
    | '/app/scan'
    | '/app/services'
    | '/app/support-chat'
    | '/app/topup'
    | '/app/transfer'
    | '/app/wallet-history'
    | '/app/water'
    | '/dealer/commission'
    | '/dealer/customers'
    | '/dealer/profile'
    | '/dealer/reports'
    | '/dealer/sub-agents'
    | '/dealer/transactions'
    | '/admin'
    | '/app'
    | '/dealer'
    | '/admin/community-electricity/$communityElectricityId'
    | '/admin/data-topups/$dataTopupId'
    | '/admin/deposits/$depositId'
    | '/admin/internet/$internetId'
    | '/admin/kyc/$kycId'
    | '/admin/topups/$topupId'
    | '/admin/users/$userId'
    | '/admin/users/new'
    | '/admin/wallets/$walletId'
    | '/admin/water/$waterId'
    | '/app/history/$activityId'
    | '/app/notifications/$notificationId'
    | '/app/profile/edit'
    | '/app/profile/email'
    | '/app/profile/kyc'
    | '/app/profile/password'
    | '/app/profile/phone'
    | '/app/profile/pin'
    | '/admin/users/$userId/edit'
    | '/admin/users/$userId/report'
    | '/admin/wallets/$walletId/edit'
    | '/admin/wallets/$walletId/transactions'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/register'
    | '/admin/commission-history'
    | '/admin/community-electricity'
    | '/admin/data-topups'
    | '/admin/dealer-profit'
    | '/admin/dealers'
    | '/admin/deposits'
    | '/admin/hierarchy'
    | '/admin/himalpay-history'
    | '/admin/internet'
    | '/admin/kyc'
    | '/admin/popups'
    | '/admin/profile'
    | '/admin/push'
    | '/admin/remittances'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/statement'
    | '/admin/support-chat'
    | '/admin/topups'
    | '/admin/transaction-history'
    | '/admin/transfers'
    | '/admin/users'
    | '/admin/wallets'
    | '/admin/water'
    | '/app/community-electricity'
    | '/app/data-topup'
    | '/app/electricity'
    | '/app/history'
    | '/app/internet'
    | '/app/load'
    | '/app/notifications'
    | '/app/profile'
    | '/app/remittance'
    | '/app/scan'
    | '/app/services'
    | '/app/support-chat'
    | '/app/topup'
    | '/app/transfer'
    | '/app/wallet-history'
    | '/app/water'
    | '/dealer/commission'
    | '/dealer/customers'
    | '/dealer/profile'
    | '/dealer/reports'
    | '/dealer/sub-agents'
    | '/dealer/transactions'
    | '/admin/'
    | '/app/'
    | '/dealer/'
    | '/admin/community-electricity_/$communityElectricityId'
    | '/admin/data-topups_/$dataTopupId'
    | '/admin/deposits_/$depositId'
    | '/admin/internet_/$internetId'
    | '/admin/kyc_/$kycId'
    | '/admin/topups_/$topupId'
    | '/admin/users_/$userId'
    | '/admin/users_/new'
    | '/admin/wallets_/$walletId'
    | '/admin/water_/$waterId'
    | '/app/history_/$activityId'
    | '/app/notifications_/$notificationId'
    | '/app/profile_/edit'
    | '/app/profile_/email'
    | '/app/profile_/kyc'
    | '/app/profile_/password'
    | '/app/profile_/phone'
    | '/app/profile_/pin'
    | '/admin/users_/$userId_/edit'
    | '/admin/users_/$userId_/report'
    | '/admin/wallets_/$walletId_/edit'
    | '/admin/wallets_/$walletId_/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  RegisterRoute: typeof RegisterRoute
  AdminCommissionHistoryRoute: typeof AdminCommissionHistoryRoute
  AdminCommunityElectricityRoute: typeof AdminCommunityElectricityRoute
  AdminDataTopupsRoute: typeof AdminDataTopupsRoute
  AdminDealerProfitRoute: typeof AdminDealerProfitRoute
  AdminDealersRoute: typeof AdminDealersRoute
  AdminDepositsRoute: typeof AdminDepositsRoute
  AdminHierarchyRoute: typeof AdminHierarchyRoute
  AdminHimalpayHistoryRoute: typeof AdminHimalpayHistoryRoute
  AdminInternetRoute: typeof AdminInternetRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminPopupsRoute: typeof AdminPopupsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminPushRoute: typeof AdminPushRoute
  AdminRemittancesRoute: typeof AdminRemittancesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStatementRoute: typeof AdminStatementRoute
  AdminSupportChatRoute: typeof AdminSupportChatRoute
  AdminTopupsRoute: typeof AdminTopupsRoute
  AdminTransactionHistoryRoute: typeof AdminTransactionHistoryRoute
  AdminTransfersRoute: typeof AdminTransfersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminWaterRoute: typeof AdminWaterRoute
  AppCommunityElectricityRoute: typeof AppCommunityElectricityRoute
  AppDataTopupRoute: typeof AppDataTopupRoute
  AppElectricityRoute: typeof AppElectricityRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppInternetRoute: typeof AppInternetRoute
  AppLoadRoute: typeof AppLoadRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRemittanceRoute: typeof AppRemittanceRoute
  AppScanRoute: typeof AppScanRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSupportChatRoute: typeof AppSupportChatRoute
  AppTopupRoute: typeof AppTopupRoute
  AppTransferRoute: typeof AppTransferRoute
  AppWalletHistoryRoute: typeof AppWalletHistoryRoute
  AppWaterRoute: typeof AppWaterRoute
  DealerCommissionRoute: typeof DealerCommissionRoute
  DealerCustomersRoute: typeof DealerCustomersRoute
  DealerProfileRoute: typeof DealerProfileRoute
  DealerReportsRoute: typeof DealerReportsRoute
  DealerSubAgentsRoute: typeof DealerSubAgentsRoute
  DealerTransactionsRoute: typeof DealerTransactionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AppIndexRoute: typeof AppIndexRoute
  DealerIndexRoute: typeof DealerIndexRoute
  AdminCommunityElectricityCommunityElectricityIdRoute: typeof AdminCommunityElectricityCommunityElectricityIdRoute
  AdminDataTopupsDataTopupIdRoute: typeof AdminDataTopupsDataTopupIdRoute
  AdminDepositsDepositIdRoute: typeof AdminDepositsDepositIdRoute
  AdminInternetInternetIdRoute: typeof AdminInternetInternetIdRoute
  AdminKycKycIdRoute: typeof AdminKycKycIdRoute
  AdminTopupsTopupIdRoute: typeof AdminTopupsTopupIdRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersNewRoute: typeof AdminUsersNewRoute
  AdminWalletsWalletIdRoute: typeof AdminWalletsWalletIdRoute
  AdminWaterWaterIdRoute: typeof AdminWaterWaterIdRoute
  AppHistoryActivityIdRoute: typeof AppHistoryActivityIdRoute
  AppNotificationsNotificationIdRoute: typeof AppNotificationsNotificationIdRoute
  AppProfileEditRoute: typeof AppProfileEditRoute
  AppProfileEmailRoute: typeof AppProfileEmailRoute
  AppProfileKycRoute: typeof AppProfileKycRoute
  AppProfilePasswordRoute: typeof AppProfilePasswordRoute
  AppProfilePhoneRoute: typeof AppProfilePhoneRoute
  AppProfilePinRoute: typeof AppProfilePinRoute
  AdminUsersUserIdEditRoute: typeof AdminUsersUserIdEditRoute
  AdminUsersUserIdReportRoute: typeof AdminUsersUserIdReportRoute
  AdminWalletsWalletIdEditRoute: typeof AdminWalletsWalletIdEditRoute
  AdminWalletsWalletIdTransactionsRoute: typeof AdminWalletsWalletIdTransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/commission-history': {
      id: '/admin/commission-history'
      path: '/admin/commission-history'
      fullPath: '/admin/commission-history'
      preLoaderRoute: typeof AdminCommissionHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/community-electricity': {
      id: '/admin/community-electricity'
      path: '/admin/community-electricity'
      fullPath: '/admin/community-electricity'
      preLoaderRoute: typeof AdminCommunityElectricityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/data-topups': {
      id: '/admin/data-topups'
      path: '/admin/data-topups'
      fullPath: '/admin/data-topups'
      preLoaderRoute: typeof AdminDataTopupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dealer-profit': {
      id: '/admin/dealer-profit'
      path: '/admin/dealer-profit'
      fullPath: '/admin/dealer-profit'
      preLoaderRoute: typeof AdminDealerProfitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dealers': {
      id: '/admin/dealers'
      path: '/admin/dealers'
      fullPath: '/admin/dealers'
      preLoaderRoute: typeof AdminDealersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/deposits': {
      id: '/admin/deposits'
      path: '/admin/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AdminDepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hierarchy': {
      id: '/admin/hierarchy'
      path: '/admin/hierarchy'
      fullPath: '/admin/hierarchy'
      preLoaderRoute: typeof AdminHierarchyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/himalpay-history': {
      id: '/admin/himalpay-history'
      path: '/admin/himalpay-history'
      fullPath: '/admin/himalpay-history'
      preLoaderRoute: typeof AdminHimalpayHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/internet': {
      id: '/admin/internet'
      path: '/admin/internet'
      fullPath: '/admin/internet'
      preLoaderRoute: typeof AdminInternetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/admin/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/popups': {
      id: '/admin/popups'
      path: '/admin/popups'
      fullPath: '/admin/popups'
      preLoaderRoute: typeof AdminPopupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/push': {
      id: '/admin/push'
      path: '/admin/push'
      fullPath: '/admin/push'
      preLoaderRoute: typeof AdminPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/remittances': {
      id: '/admin/remittances'
      path: '/admin/remittances'
      fullPath: '/admin/remittances'
      preLoaderRoute: typeof AdminRemittancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/statement': {
      id: '/admin/statement'
      path: '/admin/statement'
      fullPath: '/admin/statement'
      preLoaderRoute: typeof AdminStatementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support-chat': {
      id: '/admin/support-chat'
      path: '/admin/support-chat'
      fullPath: '/admin/support-chat'
      preLoaderRoute: typeof AdminSupportChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/topups': {
      id: '/admin/topups'
      path: '/admin/topups'
      fullPath: '/admin/topups'
      preLoaderRoute: typeof AdminTopupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transaction-history': {
      id: '/admin/transaction-history'
      path: '/admin/transaction-history'
      fullPath: '/admin/transaction-history'
      preLoaderRoute: typeof AdminTransactionHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transfers': {
      id: '/admin/transfers'
      path: '/admin/transfers'
      fullPath: '/admin/transfers'
      preLoaderRoute: typeof AdminTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/admin/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/water': {
      id: '/admin/water'
      path: '/admin/water'
      fullPath: '/admin/water'
      preLoaderRoute: typeof AdminWaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/community-electricity': {
      id: '/app/community-electricity'
      path: '/app/community-electricity'
      fullPath: '/app/community-electricity'
      preLoaderRoute: typeof AppCommunityElectricityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/data-topup': {
      id: '/app/data-topup'
      path: '/app/data-topup'
      fullPath: '/app/data-topup'
      preLoaderRoute: typeof AppDataTopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/electricity': {
      id: '/app/electricity'
      path: '/app/electricity'
      fullPath: '/app/electricity'
      preLoaderRoute: typeof AppElectricityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/history': {
      id: '/app/history'
      path: '/app/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/internet': {
      id: '/app/internet'
      path: '/app/internet'
      fullPath: '/app/internet'
      preLoaderRoute: typeof AppInternetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/load': {
      id: '/app/load'
      path: '/app/load'
      fullPath: '/app/load'
      preLoaderRoute: typeof AppLoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/app/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/remittance': {
      id: '/app/remittance'
      path: '/app/remittance'
      fullPath: '/app/remittance'
      preLoaderRoute: typeof AppRemittanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/scan': {
      id: '/app/scan'
      path: '/app/scan'
      fullPath: '/app/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/services': {
      id: '/app/services'
      path: '/app/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/support-chat': {
      id: '/app/support-chat'
      path: '/app/support-chat'
      fullPath: '/app/support-chat'
      preLoaderRoute: typeof AppSupportChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/topup': {
      id: '/app/topup'
      path: '/app/topup'
      fullPath: '/app/topup'
      preLoaderRoute: typeof AppTopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/transfer': {
      id: '/app/transfer'
      path: '/app/transfer'
      fullPath: '/app/transfer'
      preLoaderRoute: typeof AppTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/wallet-history': {
      id: '/app/wallet-history'
      path: '/app/wallet-history'
      fullPath: '/app/wallet-history'
      preLoaderRoute: typeof AppWalletHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/water': {
      id: '/app/water'
      path: '/app/water'
      fullPath: '/app/water'
      preLoaderRoute: typeof AppWaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer/': {
      id: '/dealer/'
      path: '/dealer'
      fullPath: '/dealer/'
      preLoaderRoute: typeof DealerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer/commission': {
      id: '/dealer/commission'
      path: '/dealer/commission'
      fullPath: '/dealer/commission'
      preLoaderRoute: typeof DealerCommissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer/customers': {
      id: '/dealer/customers'
      path: '/dealer/customers'
      fullPath: '/dealer/customers'
      preLoaderRoute: typeof DealerCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer/profile': {
      id: '/dealer/profile'
      path: '/dealer/profile'
      fullPath: '/dealer/profile'
      preLoaderRoute: typeof DealerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer/reports': {
      id: '/dealer/reports'
      path: '/dealer/reports'
      fullPath: '/dealer/reports'
      preLoaderRoute: typeof DealerReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer/sub-agents': {
      id: '/dealer/sub-agents'
      path: '/dealer/sub-agents'
      fullPath: '/dealer/sub-agents'
      preLoaderRoute: typeof DealerSubAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealer/transactions': {
      id: '/dealer/transactions'
      path: '/dealer/transactions'
      fullPath: '/dealer/transactions'
      preLoaderRoute: typeof DealerTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/community-electricity_/$communityElectricityId': {
      id: '/admin/community-electricity_/$communityElectricityId'
      path: '/admin/community-electricity/$communityElectricityId'
      fullPath: '/admin/community-electricity/$communityElectricityId'
      preLoaderRoute: typeof AdminCommunityElectricityCommunityElectricityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/data-topups_/$dataTopupId': {
      id: '/admin/data-topups_/$dataTopupId'
      path: '/admin/data-topups/$dataTopupId'
      fullPath: '/admin/data-topups/$dataTopupId'
      preLoaderRoute: typeof AdminDataTopupsDataTopupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/deposits_/$depositId': {
      id: '/admin/deposits_/$depositId'
      path: '/admin/deposits/$depositId'
      fullPath: '/admin/deposits/$depositId'
      preLoaderRoute: typeof AdminDepositsDepositIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/internet_/$internetId': {
      id: '/admin/internet_/$internetId'
      path: '/admin/internet/$internetId'
      fullPath: '/admin/internet/$internetId'
      preLoaderRoute: typeof AdminInternetInternetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kyc_/$kycId': {
      id: '/admin/kyc_/$kycId'
      path: '/admin/kyc/$kycId'
      fullPath: '/admin/kyc/$kycId'
      preLoaderRoute: typeof AdminKycKycIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/topups_/$topupId': {
      id: '/admin/topups_/$topupId'
      path: '/admin/topups/$topupId'
      fullPath: '/admin/topups/$topupId'
      preLoaderRoute: typeof AdminTopupsTopupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users_/$userId': {
      id: '/admin/users_/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users_/new': {
      id: '/admin/users_/new'
      path: '/admin/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AdminUsersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wallets_/$walletId': {
      id: '/admin/wallets_/$walletId'
      path: '/admin/wallets/$walletId'
      fullPath: '/admin/wallets/$walletId'
      preLoaderRoute: typeof AdminWalletsWalletIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/water_/$waterId': {
      id: '/admin/water_/$waterId'
      path: '/admin/water/$waterId'
      fullPath: '/admin/water/$waterId'
      preLoaderRoute: typeof AdminWaterWaterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/history_/$activityId': {
      id: '/app/history_/$activityId'
      path: '/app/history/$activityId'
      fullPath: '/app/history/$activityId'
      preLoaderRoute: typeof AppHistoryActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/notifications_/$notificationId': {
      id: '/app/notifications_/$notificationId'
      path: '/app/notifications/$notificationId'
      fullPath: '/app/notifications/$notificationId'
      preLoaderRoute: typeof AppNotificationsNotificationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile_/edit': {
      id: '/app/profile_/edit'
      path: '/app/profile/edit'
      fullPath: '/app/profile/edit'
      preLoaderRoute: typeof AppProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile_/email': {
      id: '/app/profile_/email'
      path: '/app/profile/email'
      fullPath: '/app/profile/email'
      preLoaderRoute: typeof AppProfileEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile_/kyc': {
      id: '/app/profile_/kyc'
      path: '/app/profile/kyc'
      fullPath: '/app/profile/kyc'
      preLoaderRoute: typeof AppProfileKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile_/password': {
      id: '/app/profile_/password'
      path: '/app/profile/password'
      fullPath: '/app/profile/password'
      preLoaderRoute: typeof AppProfilePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile_/phone': {
      id: '/app/profile_/phone'
      path: '/app/profile/phone'
      fullPath: '/app/profile/phone'
      preLoaderRoute: typeof AppProfilePhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile_/pin': {
      id: '/app/profile_/pin'
      path: '/app/profile/pin'
      fullPath: '/app/profile/pin'
      preLoaderRoute: typeof AppProfilePinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users_/$userId_/edit': {
      id: '/admin/users_/$userId_/edit'
      path: '/admin/users/$userId/edit'
      fullPath: '/admin/users/$userId/edit'
      preLoaderRoute: typeof AdminUsersUserIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users_/$userId_/report': {
      id: '/admin/users_/$userId_/report'
      path: '/admin/users/$userId/report'
      fullPath: '/admin/users/$userId/report'
      preLoaderRoute: typeof AdminUsersUserIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wallets_/$walletId_/edit': {
      id: '/admin/wallets_/$walletId_/edit'
      path: '/admin/wallets/$walletId/edit'
      fullPath: '/admin/wallets/$walletId/edit'
      preLoaderRoute: typeof AdminWalletsWalletIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wallets_/$walletId_/transactions': {
      id: '/admin/wallets_/$walletId_/transactions'
      path: '/admin/wallets/$walletId/transactions'
      fullPath: '/admin/wallets/$walletId/transactions'
      preLoaderRoute: typeof AdminWalletsWalletIdTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  RegisterRoute: RegisterRoute,
  AdminCommissionHistoryRoute: AdminCommissionHistoryRoute,
  AdminCommunityElectricityRoute: AdminCommunityElectricityRoute,
  AdminDataTopupsRoute: AdminDataTopupsRoute,
  AdminDealerProfitRoute: AdminDealerProfitRoute,
  AdminDealersRoute: AdminDealersRoute,
  AdminDepositsRoute: AdminDepositsRoute,
  AdminHierarchyRoute: AdminHierarchyRoute,
  AdminHimalpayHistoryRoute: AdminHimalpayHistoryRoute,
  AdminInternetRoute: AdminInternetRoute,
  AdminKycRoute: AdminKycRoute,
  AdminPopupsRoute: AdminPopupsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminPushRoute: AdminPushRoute,
  AdminRemittancesRoute: AdminRemittancesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStatementRoute: AdminStatementRoute,
  AdminSupportChatRoute: AdminSupportChatRoute,
  AdminTopupsRoute: AdminTopupsRoute,
  AdminTransactionHistoryRoute: AdminTransactionHistoryRoute,
  AdminTransfersRoute: AdminTransfersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminWaterRoute: AdminWaterRoute,
  AppCommunityElectricityRoute: AppCommunityElectricityRoute,
  AppDataTopupRoute: AppDataTopupRoute,
  AppElectricityRoute: AppElectricityRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppInternetRoute: AppInternetRoute,
  AppLoadRoute: AppLoadRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRemittanceRoute: AppRemittanceRoute,
  AppScanRoute: AppScanRoute,
  AppServicesRoute: AppServicesRoute,
  AppSupportChatRoute: AppSupportChatRoute,
  AppTopupRoute: AppTopupRoute,
  AppTransferRoute: AppTransferRoute,
  AppWalletHistoryRoute: AppWalletHistoryRoute,
  AppWaterRoute: AppWaterRoute,
  DealerCommissionRoute: DealerCommissionRoute,
  DealerCustomersRoute: DealerCustomersRoute,
  DealerProfileRoute: DealerProfileRoute,
  DealerReportsRoute: DealerReportsRoute,
  DealerSubAgentsRoute: DealerSubAgentsRoute,
  DealerTransactionsRoute: DealerTransactionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AppIndexRoute: AppIndexRoute,
  DealerIndexRoute: DealerIndexRoute,
  AdminCommunityElectricityCommunityElectricityIdRoute:
    AdminCommunityElectricityCommunityElectricityIdRoute,
  AdminDataTopupsDataTopupIdRoute: AdminDataTopupsDataTopupIdRoute,
  AdminDepositsDepositIdRoute: AdminDepositsDepositIdRoute,
  AdminInternetInternetIdRoute: AdminInternetInternetIdRoute,
  AdminKycKycIdRoute: AdminKycKycIdRoute,
  AdminTopupsTopupIdRoute: AdminTopupsTopupIdRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersNewRoute: AdminUsersNewRoute,
  AdminWalletsWalletIdRoute: AdminWalletsWalletIdRoute,
  AdminWaterWaterIdRoute: AdminWaterWaterIdRoute,
  AppHistoryActivityIdRoute: AppHistoryActivityIdRoute,
  AppNotificationsNotificationIdRoute: AppNotificationsNotificationIdRoute,
  AppProfileEditRoute: AppProfileEditRoute,
  AppProfileEmailRoute: AppProfileEmailRoute,
  AppProfileKycRoute: AppProfileKycRoute,
  AppProfilePasswordRoute: AppProfilePasswordRoute,
  AppProfilePhoneRoute: AppProfilePhoneRoute,
  AppProfilePinRoute: AppProfilePinRoute,
  AdminUsersUserIdEditRoute: AdminUsersUserIdEditRoute,
  AdminUsersUserIdReportRoute: AdminUsersUserIdReportRoute,
  AdminWalletsWalletIdEditRoute: AdminWalletsWalletIdEditRoute,
  AdminWalletsWalletIdTransactionsRoute: AdminWalletsWalletIdTransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
