/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDepositsRouteImport } from './routes/admin/deposits'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTopupsRouteImport } from './routes/admin/topups'
import { Route as AdminTransfersRouteImport } from './routes/admin/transfers'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminWalletsRouteImport } from './routes/admin/wallets'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppHistoryRouteImport } from './routes/app/history'
import { Route as AppLoadRouteImport } from './routes/app/load'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppServicesRouteImport } from './routes/app/services'
import { Route as AppTopupRouteImport } from './routes/app/topup'
import { Route as AppTransferRouteImport } from './routes/app/transfer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepositsRoute = AdminDepositsRouteImport.update({
  id: '/admin/deposits',
  path: '/admin/deposits',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTopupsRoute = AdminTopupsRouteImport.update({
  id: '/admin/topups',
  path: '/admin/topups',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransfersRoute = AdminTransfersRouteImport.update({
  id: '/admin/transfers',
  path: '/admin/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/admin/wallets',
  path: '/admin/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/app/history',
  path: '/app/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoadRoute = AppLoadRouteImport.update({
  id: '/app/load',
  path: '/app/load',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/app/services',
  path: '/app/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTopupRoute = AppTopupRouteImport.update({
  id: '/app/topup',
  path: '/app/topup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransferRoute = AppTransferRouteImport.update({
  id: '/app/transfer',
  path: '/app/transfer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/topups': typeof AdminTopupsRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/load': typeof AppLoadRoute
  '/app/profile': typeof AppProfileRoute
  '/app/services': typeof AppServicesRoute
  '/app/topup': typeof AppTopupRoute
  '/app/transfer': typeof AppTransferRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/topups': typeof AdminTopupsRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/load': typeof AppLoadRoute
  '/app/profile': typeof AppProfileRoute
  '/app/services': typeof AppServicesRoute
  '/app/topup': typeof AppTopupRoute
  '/app/transfer': typeof AppTransferRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/topups': typeof AdminTopupsRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/load': typeof AppLoadRoute
  '/app/profile': typeof AppProfileRoute
  '/app/services': typeof AppServicesRoute
  '/app/topup': typeof AppTopupRoute
  '/app/transfer': typeof AppTransferRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/deposits'
    | '/admin/settings'
    | '/admin/topups'
    | '/admin/transfers'
    | '/admin/users'
    | '/admin/wallets'
    | '/app/history'
    | '/app/load'
    | '/app/profile'
    | '/app/services'
    | '/app/topup'
    | '/app/transfer'
    | '/admin/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/deposits'
    | '/admin/settings'
    | '/admin/topups'
    | '/admin/transfers'
    | '/admin/users'
    | '/admin/wallets'
    | '/app/history'
    | '/app/load'
    | '/app/profile'
    | '/app/services'
    | '/app/topup'
    | '/app/transfer'
    | '/admin'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/admin/deposits'
    | '/admin/settings'
    | '/admin/topups'
    | '/admin/transfers'
    | '/admin/users'
    | '/admin/wallets'
    | '/app/history'
    | '/app/load'
    | '/app/profile'
    | '/app/services'
    | '/app/topup'
    | '/app/transfer'
    | '/admin/'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDepositsRoute: typeof AdminDepositsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTopupsRoute: typeof AdminTopupsRoute
  AdminTransfersRoute: typeof AdminTransfersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppLoadRoute: typeof AppLoadRoute
  AppProfileRoute: typeof AppProfileRoute
  AppServicesRoute: typeof AppServicesRoute
  AppTopupRoute: typeof AppTopupRoute
  AppTransferRoute: typeof AppTransferRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/deposits': {
      id: '/admin/deposits'
      path: '/admin/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AdminDepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/topups': {
      id: '/admin/topups'
      path: '/admin/topups'
      fullPath: '/admin/topups'
      preLoaderRoute: typeof AdminTopupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transfers': {
      id: '/admin/transfers'
      path: '/admin/transfers'
      fullPath: '/admin/transfers'
      preLoaderRoute: typeof AdminTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/admin/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/history': {
      id: '/app/history'
      path: '/app/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/load': {
      id: '/app/load'
      path: '/app/load'
      fullPath: '/app/load'
      preLoaderRoute: typeof AppLoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/services': {
      id: '/app/services'
      path: '/app/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/topup': {
      id: '/app/topup'
      path: '/app/topup'
      fullPath: '/app/topup'
      preLoaderRoute: typeof AppTopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/transfer': {
      id: '/app/transfer'
      path: '/app/transfer'
      fullPath: '/app/transfer'
      preLoaderRoute: typeof AppTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDepositsRoute: AdminDepositsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTopupsRoute: AdminTopupsRoute,
  AdminTransfersRoute: AdminTransfersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppLoadRoute: AppLoadRoute,
  AppProfileRoute: AppProfileRoute,
  AppServicesRoute: AppServicesRoute,
  AppTopupRoute: AppTopupRoute,
  AppTransferRoute: AppTransferRoute,
  AdminIndexRoute: AdminIndexRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
