/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDepositsRouteImport } from './routes/admin/deposits'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminRemittancesRouteImport } from './routes/admin/remittances'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminTopupsRouteImport } from './routes/admin/topups'
import { Route as AdminTransfersRouteImport } from './routes/admin/transfers'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminWalletsRouteImport } from './routes/admin/wallets'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppDataTopupRouteImport } from './routes/app/data-topup'
import { Route as AppHistoryRouteImport } from './routes/app/history'
import { Route as AppInternetRouteImport } from './routes/app/internet'
import { Route as AppLoadRouteImport } from './routes/app/load'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppRemittanceRouteImport } from './routes/app/remittance'
import { Route as AppServicesRouteImport } from './routes/app/services'
import { Route as AppTopupRouteImport } from './routes/app/topup'
import { Route as AppTransferRouteImport } from './routes/app/transfer'
import { Route as AdminDepositsDepositIdRouteImport } from './routes/admin/deposits_.$depositId'
import { Route as AdminTopupsTopupIdRouteImport } from './routes/admin/topups_.$topupId'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users_.$userId'
import { Route as AdminUsersNewRouteImport } from './routes/admin/users_.new'
import { Route as AdminWalletsWalletIdRouteImport } from './routes/admin/wallets_.$walletId'
import { Route as AppHistoryActivityIdRouteImport } from './routes/app/history_.$activityId'
import { Route as AppNotificationsNotificationIdRouteImport } from './routes/app/notifications_.$notificationId'
import { Route as AppProfileEditRouteImport } from './routes/app/profile_.edit'
import { Route as AppProfilePasswordRouteImport } from './routes/app/profile_.password'
import { Route as AppProfilePhoneRouteImport } from './routes/app/profile_.phone'
import { Route as AdminUsersUserIdEditRouteImport } from './routes/admin/users_.$userId_.edit'
import { Route as AdminWalletsWalletIdEditRouteImport } from './routes/admin/wallets_.$walletId_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepositsRoute = AdminDepositsRouteImport.update({
  id: '/admin/deposits',
  path: '/admin/deposits',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRemittancesRoute = AdminRemittancesRouteImport.update({
  id: '/admin/remittances',
  path: '/admin/remittances',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTopupsRoute = AdminTopupsRouteImport.update({
  id: '/admin/topups',
  path: '/admin/topups',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransfersRoute = AdminTransfersRouteImport.update({
  id: '/admin/transfers',
  path: '/admin/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/admin/wallets',
  path: '/admin/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDataTopupRoute = AppDataTopupRouteImport.update({
  id: '/app/data-topup',
  path: '/app/data-topup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/app/history',
  path: '/app/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInternetRoute = AppInternetRouteImport.update({
  id: '/app/internet',
  path: '/app/internet',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoadRoute = AppLoadRouteImport.update({
  id: '/app/load',
  path: '/app/load',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/app/notifications',
  path: '/app/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRemittanceRoute = AppRemittanceRouteImport.update({
  id: '/app/remittance',
  path: '/app/remittance',
  getParentRoute: () => rootRouteImport,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/app/services',
  path: '/app/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTopupRoute = AppTopupRouteImport.update({
  id: '/app/topup',
  path: '/app/topup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransferRoute = AppTransferRouteImport.update({
  id: '/app/transfer',
  path: '/app/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepositsDepositIdRoute = AdminDepositsDepositIdRouteImport.update({
  id: '/admin/deposits_/$depositId',
  path: '/admin/deposits/$depositId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTopupsTopupIdRoute = AdminTopupsTopupIdRouteImport.update({
  id: '/admin/topups_/$topupId',
  path: '/admin/topups/$topupId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/admin/users_/$userId',
  path: '/admin/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersNewRoute = AdminUsersNewRouteImport.update({
  id: '/admin/users_/new',
  path: '/admin/users/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletsWalletIdRoute = AdminWalletsWalletIdRouteImport.update({
  id: '/admin/wallets_/$walletId',
  path: '/admin/wallets/$walletId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHistoryActivityIdRoute = AppHistoryActivityIdRouteImport.update({
  id: '/app/history_/$activityId',
  path: '/app/history/$activityId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotificationsNotificationIdRoute =
  AppNotificationsNotificationIdRouteImport.update({
    id: '/app/notifications_/$notificationId',
    path: '/app/notifications/$notificationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppProfileEditRoute = AppProfileEditRouteImport.update({
  id: '/app/profile_/edit',
  path: '/app/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfilePasswordRoute = AppProfilePasswordRouteImport.update({
  id: '/app/profile_/password',
  path: '/app/profile/password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfilePhoneRoute = AppProfilePhoneRouteImport.update({
  id: '/app/profile_/phone',
  path: '/app/profile/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdEditRoute = AdminUsersUserIdEditRouteImport.update({
  id: '/admin/users_/$userId_/edit',
  path: '/admin/users/$userId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletsWalletIdEditRoute =
  AdminWalletsWalletIdEditRouteImport.update({
    id: '/admin/wallets_/$walletId_/edit',
    path: '/admin/wallets/$walletId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/remittances': typeof AdminRemittancesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/topups': typeof AdminTopupsRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/app/data-topup': typeof AppDataTopupRoute
  '/app/history': typeof AppHistoryRoute
  '/app/internet': typeof AppInternetRoute
  '/app/load': typeof AppLoadRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/remittance': typeof AppRemittanceRoute
  '/app/services': typeof AppServicesRoute
  '/app/topup': typeof AppTopupRoute
  '/app/transfer': typeof AppTransferRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/deposits/$depositId': typeof AdminDepositsDepositIdRoute
  '/admin/topups/$topupId': typeof AdminTopupsTopupIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/wallets/$walletId': typeof AdminWalletsWalletIdRoute
  '/app/history/$activityId': typeof AppHistoryActivityIdRoute
  '/app/notifications/$notificationId': typeof AppNotificationsNotificationIdRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/profile/password': typeof AppProfilePasswordRoute
  '/app/profile/phone': typeof AppProfilePhoneRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
  '/admin/wallets/$walletId/edit': typeof AdminWalletsWalletIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/remittances': typeof AdminRemittancesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/topups': typeof AdminTopupsRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/app/data-topup': typeof AppDataTopupRoute
  '/app/history': typeof AppHistoryRoute
  '/app/internet': typeof AppInternetRoute
  '/app/load': typeof AppLoadRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/remittance': typeof AppRemittanceRoute
  '/app/services': typeof AppServicesRoute
  '/app/topup': typeof AppTopupRoute
  '/app/transfer': typeof AppTransferRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/deposits/$depositId': typeof AdminDepositsDepositIdRoute
  '/admin/topups/$topupId': typeof AdminTopupsTopupIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/wallets/$walletId': typeof AdminWalletsWalletIdRoute
  '/app/history/$activityId': typeof AppHistoryActivityIdRoute
  '/app/notifications/$notificationId': typeof AppNotificationsNotificationIdRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/profile/password': typeof AppProfilePasswordRoute
  '/app/profile/phone': typeof AppProfilePhoneRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
  '/admin/wallets/$walletId/edit': typeof AdminWalletsWalletIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/remittances': typeof AdminRemittancesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/topups': typeof AdminTopupsRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/app/data-topup': typeof AppDataTopupRoute
  '/app/history': typeof AppHistoryRoute
  '/app/internet': typeof AppInternetRoute
  '/app/load': typeof AppLoadRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/remittance': typeof AppRemittanceRoute
  '/app/services': typeof AppServicesRoute
  '/app/topup': typeof AppTopupRoute
  '/app/transfer': typeof AppTransferRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/deposits_/$depositId': typeof AdminDepositsDepositIdRoute
  '/admin/topups_/$topupId': typeof AdminTopupsTopupIdRoute
  '/admin/users_/$userId': typeof AdminUsersUserIdRoute
  '/admin/users_/new': typeof AdminUsersNewRoute
  '/admin/wallets_/$walletId': typeof AdminWalletsWalletIdRoute
  '/app/history_/$activityId': typeof AppHistoryActivityIdRoute
  '/app/notifications_/$notificationId': typeof AppNotificationsNotificationIdRoute
  '/app/profile_/edit': typeof AppProfileEditRoute
  '/app/profile_/password': typeof AppProfilePasswordRoute
  '/app/profile_/phone': typeof AppProfilePhoneRoute
  '/admin/users_/$userId_/edit': typeof AdminUsersUserIdEditRoute
  '/admin/wallets_/$walletId_/edit': typeof AdminWalletsWalletIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/register'
    | '/admin/deposits'
    | '/admin/profile'
    | '/admin/remittances'
    | '/admin/settings'
    | '/admin/topups'
    | '/admin/transfers'
    | '/admin/users'
    | '/admin/wallets'
    | '/app/data-topup'
    | '/app/history'
    | '/app/internet'
    | '/app/load'
    | '/app/notifications'
    | '/app/profile'
    | '/app/remittance'
    | '/app/services'
    | '/app/topup'
    | '/app/transfer'
    | '/admin/'
    | '/app/'
    | '/admin/deposits/$depositId'
    | '/admin/topups/$topupId'
    | '/admin/users/$userId'
    | '/admin/users/new'
    | '/admin/wallets/$walletId'
    | '/app/history/$activityId'
    | '/app/notifications/$notificationId'
    | '/app/profile/edit'
    | '/app/profile/password'
    | '/app/profile/phone'
    | '/admin/users/$userId/edit'
    | '/admin/wallets/$walletId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/register'
    | '/admin/deposits'
    | '/admin/profile'
    | '/admin/remittances'
    | '/admin/settings'
    | '/admin/topups'
    | '/admin/transfers'
    | '/admin/users'
    | '/admin/wallets'
    | '/app/data-topup'
    | '/app/history'
    | '/app/internet'
    | '/app/load'
    | '/app/notifications'
    | '/app/profile'
    | '/app/remittance'
    | '/app/services'
    | '/app/topup'
    | '/app/transfer'
    | '/admin'
    | '/app'
    | '/admin/deposits/$depositId'
    | '/admin/topups/$topupId'
    | '/admin/users/$userId'
    | '/admin/users/new'
    | '/admin/wallets/$walletId'
    | '/app/history/$activityId'
    | '/app/notifications/$notificationId'
    | '/app/profile/edit'
    | '/app/profile/password'
    | '/app/profile/phone'
    | '/admin/users/$userId/edit'
    | '/admin/wallets/$walletId/edit'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/register'
    | '/admin/deposits'
    | '/admin/profile'
    | '/admin/remittances'
    | '/admin/settings'
    | '/admin/topups'
    | '/admin/transfers'
    | '/admin/users'
    | '/admin/wallets'
    | '/app/data-topup'
    | '/app/history'
    | '/app/internet'
    | '/app/load'
    | '/app/notifications'
    | '/app/profile'
    | '/app/remittance'
    | '/app/services'
    | '/app/topup'
    | '/app/transfer'
    | '/admin/'
    | '/app/'
    | '/admin/deposits_/$depositId'
    | '/admin/topups_/$topupId'
    | '/admin/users_/$userId'
    | '/admin/users_/new'
    | '/admin/wallets_/$walletId'
    | '/app/history_/$activityId'
    | '/app/notifications_/$notificationId'
    | '/app/profile_/edit'
    | '/app/profile_/password'
    | '/app/profile_/phone'
    | '/admin/users_/$userId_/edit'
    | '/admin/wallets_/$walletId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  RegisterRoute: typeof RegisterRoute
  AdminDepositsRoute: typeof AdminDepositsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminRemittancesRoute: typeof AdminRemittancesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTopupsRoute: typeof AdminTopupsRoute
  AdminTransfersRoute: typeof AdminTransfersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AppDataTopupRoute: typeof AppDataTopupRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppInternetRoute: typeof AppInternetRoute
  AppLoadRoute: typeof AppLoadRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRemittanceRoute: typeof AppRemittanceRoute
  AppServicesRoute: typeof AppServicesRoute
  AppTopupRoute: typeof AppTopupRoute
  AppTransferRoute: typeof AppTransferRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AppIndexRoute: typeof AppIndexRoute
  AdminDepositsDepositIdRoute: typeof AdminDepositsDepositIdRoute
  AdminTopupsTopupIdRoute: typeof AdminTopupsTopupIdRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersNewRoute: typeof AdminUsersNewRoute
  AdminWalletsWalletIdRoute: typeof AdminWalletsWalletIdRoute
  AppHistoryActivityIdRoute: typeof AppHistoryActivityIdRoute
  AppNotificationsNotificationIdRoute: typeof AppNotificationsNotificationIdRoute
  AppProfileEditRoute: typeof AppProfileEditRoute
  AppProfilePasswordRoute: typeof AppProfilePasswordRoute
  AppProfilePhoneRoute: typeof AppProfilePhoneRoute
  AdminUsersUserIdEditRoute: typeof AdminUsersUserIdEditRoute
  AdminWalletsWalletIdEditRoute: typeof AdminWalletsWalletIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/deposits': {
      id: '/admin/deposits'
      path: '/admin/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AdminDepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/remittances': {
      id: '/admin/remittances'
      path: '/admin/remittances'
      fullPath: '/admin/remittances'
      preLoaderRoute: typeof AdminRemittancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/topups': {
      id: '/admin/topups'
      path: '/admin/topups'
      fullPath: '/admin/topups'
      preLoaderRoute: typeof AdminTopupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transfers': {
      id: '/admin/transfers'
      path: '/admin/transfers'
      fullPath: '/admin/transfers'
      preLoaderRoute: typeof AdminTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/admin/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/data-topup': {
      id: '/app/data-topup'
      path: '/app/data-topup'
      fullPath: '/app/data-topup'
      preLoaderRoute: typeof AppDataTopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/history': {
      id: '/app/history'
      path: '/app/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/internet': {
      id: '/app/internet'
      path: '/app/internet'
      fullPath: '/app/internet'
      preLoaderRoute: typeof AppInternetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/load': {
      id: '/app/load'
      path: '/app/load'
      fullPath: '/app/load'
      preLoaderRoute: typeof AppLoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/app/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/remittance': {
      id: '/app/remittance'
      path: '/app/remittance'
      fullPath: '/app/remittance'
      preLoaderRoute: typeof AppRemittanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/services': {
      id: '/app/services'
      path: '/app/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/topup': {
      id: '/app/topup'
      path: '/app/topup'
      fullPath: '/app/topup'
      preLoaderRoute: typeof AppTopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/transfer': {
      id: '/app/transfer'
      path: '/app/transfer'
      fullPath: '/app/transfer'
      preLoaderRoute: typeof AppTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/deposits_/$depositId': {
      id: '/admin/deposits_/$depositId'
      path: '/admin/deposits/$depositId'
      fullPath: '/admin/deposits/$depositId'
      preLoaderRoute: typeof AdminDepositsDepositIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/topups_/$topupId': {
      id: '/admin/topups_/$topupId'
      path: '/admin/topups/$topupId'
      fullPath: '/admin/topups/$topupId'
      preLoaderRoute: typeof AdminTopupsTopupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users_/$userId': {
      id: '/admin/users_/$userId'
      path: '/admin/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users_/new': {
      id: '/admin/users_/new'
      path: '/admin/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AdminUsersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wallets_/$walletId': {
      id: '/admin/wallets_/$walletId'
      path: '/admin/wallets/$walletId'
      fullPath: '/admin/wallets/$walletId'
      preLoaderRoute: typeof AdminWalletsWalletIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/history_/$activityId': {
      id: '/app/history_/$activityId'
      path: '/app/history/$activityId'
      fullPath: '/app/history/$activityId'
      preLoaderRoute: typeof AppHistoryActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/notifications_/$notificationId': {
      id: '/app/notifications_/$notificationId'
      path: '/app/notifications/$notificationId'
      fullPath: '/app/notifications/$notificationId'
      preLoaderRoute: typeof AppNotificationsNotificationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile_/edit': {
      id: '/app/profile_/edit'
      path: '/app/profile/edit'
      fullPath: '/app/profile/edit'
      preLoaderRoute: typeof AppProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile_/password': {
      id: '/app/profile_/password'
      path: '/app/profile/password'
      fullPath: '/app/profile/password'
      preLoaderRoute: typeof AppProfilePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile_/phone': {
      id: '/app/profile_/phone'
      path: '/app/profile/phone'
      fullPath: '/app/profile/phone'
      preLoaderRoute: typeof AppProfilePhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users_/$userId_/edit': {
      id: '/admin/users_/$userId_/edit'
      path: '/admin/users/$userId/edit'
      fullPath: '/admin/users/$userId/edit'
      preLoaderRoute: typeof AdminUsersUserIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wallets_/$walletId_/edit': {
      id: '/admin/wallets_/$walletId_/edit'
      path: '/admin/wallets/$walletId/edit'
      fullPath: '/admin/wallets/$walletId/edit'
      preLoaderRoute: typeof AdminWalletsWalletIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  RegisterRoute: RegisterRoute,
  AdminDepositsRoute: AdminDepositsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminRemittancesRoute: AdminRemittancesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTopupsRoute: AdminTopupsRoute,
  AdminTransfersRoute: AdminTransfersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AppDataTopupRoute: AppDataTopupRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppInternetRoute: AppInternetRoute,
  AppLoadRoute: AppLoadRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRemittanceRoute: AppRemittanceRoute,
  AppServicesRoute: AppServicesRoute,
  AppTopupRoute: AppTopupRoute,
  AppTransferRoute: AppTransferRoute,
  AdminIndexRoute: AdminIndexRoute,
  AppIndexRoute: AppIndexRoute,
  AdminDepositsDepositIdRoute: AdminDepositsDepositIdRoute,
  AdminTopupsTopupIdRoute: AdminTopupsTopupIdRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersNewRoute: AdminUsersNewRoute,
  AdminWalletsWalletIdRoute: AdminWalletsWalletIdRoute,
  AppHistoryActivityIdRoute: AppHistoryActivityIdRoute,
  AppNotificationsNotificationIdRoute: AppNotificationsNotificationIdRoute,
  AppProfileEditRoute: AppProfileEditRoute,
  AppProfilePasswordRoute: AppProfilePasswordRoute,
  AppProfilePhoneRoute: AppProfilePhoneRoute,
  AdminUsersUserIdEditRoute: AdminUsersUserIdEditRoute,
  AdminWalletsWalletIdEditRoute: AdminWalletsWalletIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
