"""
Django settings for mysewa_backend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from urllib.parse import urlparse
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from server/.env
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


def _normalize_url(url: str) -> str:
    return (url or '').strip().rstrip('/')


def _origin_from_url(url: str) -> str:
    """Return scheme://host[:port] from a full URL (path is ignored)."""
    raw = (url or '').strip()
    if not raw:
        return ''
    parsed = urlparse(raw if '://' in raw else f'https://{raw}')
    if not parsed.scheme or not parsed.netloc:
        return ''
    return f'{parsed.scheme}://{parsed.netloc}'


def _host_from_url(url: str) -> str | None:
    origin = _origin_from_url(url)
    return urlparse(origin).hostname if origin else None


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k+i9woi)x(trwi=*4g3r!)oqrf9u)j)yvg$9f^%(3%y5c9e56@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Public URLs (from .env) — frontend SPA and Django API/admin host
FRONTEND_URL = _normalize_url(
    os.environ.get('FRONTEND_URL', 'https://mysewa.sewabyapar.com/')
)
# May include the admin path (/database); origin is derived for CORS/hosts.
BACKEND_URL = _normalize_url(
    os.environ.get('BACKEND_URL', 'https://mysewaserver.sewabyapar.com/database/')
)
FRONTEND_ORIGIN = _origin_from_url(FRONTEND_URL) or FRONTEND_URL
BACKEND_ORIGIN = _origin_from_url(BACKEND_URL) or BACKEND_URL
# Admin lives at BACKEND_URL when that env value already includes /database
ADMIN_URL = BACKEND_URL if BACKEND_URL.rstrip('/').endswith('/database') else f'{BACKEND_ORIGIN}/database'

_allowed_hosts_env = os.environ.get('ALLOWED_HOSTS', '').strip()
if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]
else:
    _derived_hosts = [
        h for h in (_host_from_url(FRONTEND_URL), _host_from_url(BACKEND_URL)) if h
    ]
    ALLOWED_HOSTS = _derived_hosts or ['*']
    if DEBUG:
        for _local in ('localhost', '127.0.0.1'):
            if _local not in ALLOWED_HOSTS:
                ALLOWED_HOSTS.append(_local)


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'core'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.AppSettingsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# CORS / CSRF from configured frontend + backend origins
CORS_ALLOWED_ORIGINS = [
    o for o in (FRONTEND_ORIGIN, BACKEND_ORIGIN) if o
]
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'true').lower() in (
    '1',
    'true',
    'yes',
)
CSRF_TRUSTED_ORIGINS = [
    o for o in (FRONTEND_ORIGIN, BACKEND_ORIGIN) if o
]
if DEBUG:
    for _dev_origin in (
        'http://127.0.0.1:8000',
        'http://localhost:8000',
        'http://127.0.0.1:5173',
        'http://localhost:5173',
    ):
        if _dev_origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_dev_origin)
        if _dev_origin not in CORS_ALLOWED_ORIGINS:
            CORS_ALLOWED_ORIGINS.append(_dev_origin)

ROOT_URLCONF = 'mysewa_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysewa_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
   os.path.join(BASE_DIR, 'static')
] 
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'core.CustomUser'

# Authentication Backends
# Custom backend for phone-based authentication (highest priority)
AUTHENTICATION_BACKENDS = [
    'core.backends.PhoneBackend',  # Custom phone-based authentication
    'django.contrib.auth.backends.ModelBackend',  # Fallback to default backend
]

# Service Hub API Configuration (legacy — topups now use HimalPay)
SERVICE_HUB_BASE_URL = 'https://servicehubapiuat.yoapp.com.np'
SERVICE_HUB_API_USERNAME = 'sajilo'  # Set your Service Hub API username here (required for login)
SERVICE_HUB_API_PASSWORD = 'Sajilo#121'  # Set your Service Hub API password here (required for login)
SERVICE_HUB_PRIVATE_KEY_PATH = os.path.join(BASE_DIR, 'service_private_key.txt')  # Optional: custom path to private key file
SERVICE_HUB_BYPASS_API = True  # Set to True to bypass API calls and return mock success (for testing/development)

# HimalPay Reseller API Configuration (loaded from .env)
HIMALPAY_BASE_URL = os.environ.get(
    'HIMALPAY_BASE_URL',
    'https://api.himalpay.com.np/api/v1',
)
HIMALPAY_API_KEY = os.environ.get('HIMALPAY_API_KEY', '').strip()
HIMALPAY_BYPASS_API = os.environ.get('HIMALPAY_BYPASS_API', 'false').lower() in ('1', 'true', 'yes')
HIMALPAY_TIMEOUT = int(os.environ.get('HIMALPAY_TIMEOUT', '60'))
# Key loading priority (in order):
# 1. service hub api/Private key.txt (workspace root) - PRIMARY LOCATION for updated keys
# 2. SERVICE_HUB_PRIVATE_KEY_PATH (if set and file exists)
# 3. mysewa_backend/service_hub_key.txt (backend project directory)
# 4. SERVICE_HUB_PRIVATE_KEY (hardcoded in settings, fallback only)
# SERVICE_HUB_PRIVATE_KEY = '-----BEGIN RSA PRIVATE KEY----- MIIEpAIBAAKCAQEAm34KWA8Q1ntnsQlW1QrwJ++JAzav0vX3OzE/rxFQT2M9+VHYtDiaD8j669RoGLsJqZJOXtfcjeDnGLww48m2yvMx7+30xDtDz2wYKY3jfYXp1Og6pY5sYv4Vtn+jNYBxZdj5cZOeENWnahdIoqNS6tbzgrisOFA09oEfCf7wGSAhDc8QhWzGH94ZaLRtMWykxPH/zXdm7KYrYhjHYD9bQq6aP4STgpc4ekk1m0/qHPyVoTaT8YLiXmlKnGbyRew3d2+exyYdN6AU/5P/bsJ3ZyG3tE1m6gWjPnFhzolAzFylUS54JKpueC+838eQrdKLnN5mr+pAXUPNBHjLvgUhpQIDAQABAoIBADXrYR7kKoyVwoFLocbCwkC2+aYZoqLfFFp8W38T2+uLmIQKc8EbF6F9qjV5NJfO1CzvRSnyZNL2OG0FZVa4LiD2cEypEYWyn3MgIsjWIRr4AvwHg77BQqiZP2JHpIr6/Ve6A9X0wI1J6YIKjO+I/0ncPBkKfP4SIiuQ3viSZSPwy89kSbZl3K5hH4BxboZcZ99if7963tUsdlz+gwkbOGViif9lbDXcdcbgkOKkpBmMxP6+qz2r2b2a9Gm1zAHdFHBE6rmbeN1XIArmLlR+HlAiWoBB0ccFNkdCcN0HJs4QIPy9O2QpGb71TKUYO7bLj4BUC1hhaBgJTP+gS+WYVIkCgYEAwHYbTqDM53SgnMMvXZmLCI+8ZCO0qhaR3dmc2wYMRIotiIQwoMemxV6upscGL74OwGmEd2PZeYT8rPPw+gUUddn4c5jnefQGfllkt37YigHtEMEUw6Ev53C/1HNe+xLHfi/CfKjpiCxX9Ez2XfA/U/loE2VUo/AYq8VSCgtlRyMCgYEAztN+ZUpCP6HTPYB+YZ/p670Ogcy93igSPEJivDYsIgBFmVYK+vYje4TJ/BUh7tbdcq4XPtyRyHJ1LUCH7cIryXwycXdOCt3ystsDZxZpRrLPvIa3eii9+R9xs+6kOaK0dOoQn+5sAqjxzyuOQTFWrYkQIuTJ6ywn5YLcGZuv5JcCgYAgg9OZNRFpCQsZcOBPr+ENUTtCr8WV9rouANW/KwZnjfCjX7HXd+N09MoM4xLoffOADlOS2AulvBH0JkJP+wu53VlcLjjtIYz3S6L4XTW4Gxsx+WzIoDK3pxTBj7w8LrAFYYw6A09w8gzp+RamSDBqv3gVzsi96ZJBctSpXcN+gQKBgQCNLYKGo4TLKKwnvBEIlH65QqinY1lrTpD7/xikfpnrb6ISg9Ak9GTOCJtTbh1midZJVJpbd3YvjCl+BSGD4tm+w/8uwpBMDKqA+cy9zmd4MdBpUM/nG+5pIdScTNZe3Tgu4iMM+FNUEXxVvNZym7od5IRWPTOzSsXE/Wk+Na5/6wKBgQCPY7rX28WdJcBwdCpjgxIQ0NgqnpuHZ4QCCv8FTXCheYZzrawP8cwMQcXj4ZvhvH+8PQTMF275f+GD4phE3WzscKMoCZ0kSQdWnDpQ9KGTo6EwBRP6wFEJE7Wvu/wRZOUTV1lEY0Mb48uS4elErF/RWF873MYZsZpPOJlMaJAHAQ==----- END RSA PRIVATE KEY-----'

# Email (notifications). Override via env in production.
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'true').lower() in ('1', 'true', 'yes')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'MySewa <noreply@mysewa.local>')

